### ISSUE TITLE
Scan/Filter and Pagination not available in docker

### ISSUE THREAD

**Issue by ivansabik** [aaronshaf/dynamodb-admin#22]
First of all props for the great tool! We've been using it lately for local development but somehow noticed that the docker image is not showing the Filter/Scan section, neither does the Pagination. Actually the view is completely different. This makes me wonder if it's just pointing to an older version of `dynamodb-admin`, would be glad to take a look but any hint to where the issue comes from would be appreciated.

## Using the docker image
```yaml
version: '2'
services:
  dynamodb:
    image: tray/dynamodb-local
    ports:
      - 7777:7777
    volumes:
      - ./data/dynamodb/:/opt/dynamodb
    restart: always
    command: -port 7777 -dbPath /opt/dynamodb
  db-ui:
    image: aaronshaf/dynamodb-admin
    ports:
      - 8998:8001
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:7777
```

![image](https://user-images.githubusercontent.com/815440/31402925-24842740-adbd-11e7-88cd-6a9699b0cfa4.png)

## Installing manually

1. `npm install dynamodb-admin -g`
2. `AWS_ACCESS_KEY_ID=supersecret AWS_SECRET_ACCESS_KEY=supersecret DYNAMO_ENDPOINT=http://localhost:7777 dynamodb-admin`
![image](https://user-images.githubusercontent.com/815440/31402814-c134ae8a-adbc-11e7-9445-02c1ff1ae6c8.png)

**Comment by ivansabik** [comment]
Workaround is using the git repo to build the docker image instead of using `image: aaronshaf/dynamodb-admin`, something like:
```yaml
  db-ui:
    build:
      context: https://github.com/aaronshaf/dynamodb-admin.git
    ports:
      - 8998:8001
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:7777
```
