### ISSUE TITLE
Docker image not working when using an external .env variable

### ISSUE THREAD

**Issue by jcjp** [aaronshaf/dynamodb-admin#274]
I tried the docker image using docker-compose to build and run the image.

Its working when directly adding the environments on the docker-compose file:

```
  ddb_local_ad:
    container_name: ddb_local_ad
    restart: always
    depends_on:
      - <local_dynamo>
    image: aaronshaf/dynamodb-admin
    ports:
      - <PORT>:<PORT>
    # Includes DYNAMO_ENDPOINT: <local_dynamo>:<local_dynamo_PORT>
    env_file:
      - ./.env
    # Using environment below works properly
    # environment:
    #   DYNAMO_ENDPOINT: <local_dynamo>:<local_dynamo_PORT>
```

Is adding the `environment` only way to run the docker image?
