### ISSUE TITLE
dynamodb-admin stopped working

### ISSUE THREAD

**Issue by dmtr-kr** [aaronshaf/dynamodb-admin#473]
**dynamodb-admin** docker image stopped working. My colleagues in the team also have this problem. We guess that it is due to the implementation — we swapped the docker image 'aaronshaf/dynamodb-admin:latest' with the outdated image 'instructure/dynamo-local-admin:latest', **and it worked again**.

If you now try to open 'dynamo-db' on 'localhost' under the correct port, this is what it looks like.
![image](https://github.com/user-attachments/assets/31eb07be-091b-4a67-84d6-8eb33c61ab5a)

The container starts and throws no other errors.
![image](https://github.com/user-attachments/assets/c5b8ed05-c66b-443e-ae06-624feeebcf1a)

This is the configuration in 'docker-compose.yaml'
![image](https://github.com/user-attachments/assets/a0da6d80-bbb0-46b6-b22d-5767461a6881)

**Current local setup**
- MS Windows 10
- Docker Desktop: Current version: 4.34.3 (170107)
- Docker Engine v27.2.0

**Comment by rchl** [comment]
What the `latest` resolves to in your case? Can you check which is the latest version that still works?
Also feel free to share the whole `docker-compose.yaml` in text form if it reproduces using that one.

**Comment by Kenpal-ElenaTokumura** [comment]
I'm probably experiencing a similar issue.

ECONNREFUSED error occurs from Docker image version 5.0.1.
When I reverted back to version 4.6.2 it worked fine.

```yml
services:
  dynamodb:
    container_name: dynamodb-local
    image: "amazon/dynamodb-local:latest"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    ports:
      - "8000:8000"
    volumes:
      - "./data/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  dynamodb-admin:
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=dynamodb:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb
```

It looks like dynamodb-admin is failing to connect to the dynamodb container.
